# list the Base networks available to gateway
networks:
  mainnet:
    chainID: 8453
    nodeURL: https://mainnet.base.org
    tokenListType: 'FILE'
    tokenListSource: '/home/gateway/conf/lists/base_tokens_mainnet.json'
    nativeCurrencySymbol: 'ETH'
  sepolia:
    chainID: 84532
    nodeURL: https://sepolia.base.org
    tokenListType: 'FILE'
    tokenListSource: '/home/gateway/conf/lists/base_tokens_sepolia.json'
    nativeCurrencySymbol: 'MATIC'

manualGasPrice: 400
gasLimitTransaction: 3000000
